stages:
  - build

build_lean_project:
  image: debian:bookworm
  stage: build
  before_script:
    - apt-get update && apt-get install -y curl
    - curl -O https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
    - sh elan-init.sh -y && rm elan-init.sh
    - elan toolchain install stable && elan toolchain install nightly
    - chmod -R 777 /opt/elan
  script:
    - lake clean
    - lake update
    - lake build