stages:
  - build

build_lean_project:
  image: debian:bookworm
  stage: build
  before_script:
    - apt-get update && apt-get install -y curl
    - curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
  script:
    - lake update
    - lake build