stages:
  - build

update-and-build:
  image:
    name: leanprovercommunity/lean:debian
    entrypoint: ["/bin/sh", "-c"]
  stage: build
  only:
    - master
  script:
    - lake update
    - lake build