stages:
  - build

update-and-build:
  image:
    name: registry.git.zib.de/docker/ais2t/lean
    entrypoint: ["/bin/bash", "-c"]
  stage: build
  only:
    - master
  script:
    - 'lake update'
    - 'lake build'