stages:
  - build

build_lean_project:
  image: python:3.11-bookworm
  stage: build
  before_script:
    - apt-get update && apt-get install -y curl git
    - curl -sS https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh | sh -s -- -y
    - export PATH="$HOME/.elan/bin:$PATH"
  script:
    - lake clean && lake update && lake build