import TheBook.ToMathlib.EdgeFinset
import TheBook.ToMathlib.WeightedDoubleCounting

import TheBook.NumberTheory.InfinitudePrimes.Statement
import TheBook.NumberTheory.InfinitudePrimes.EuclidProof
import TheBook.NumberTheory.InfinitudePrimes.GoldbachProof
import TheBook.NumberTheory.InfinitudePrimes.FolkloreMersenneProof
import TheBook.NumberTheory.InfinitudePrimes.FurstenbergProof

import TheBook.GraphTheory.Mantel.Basic
import TheBook.GraphTheory.Mantel.CauchyInequality
import TheBook.GraphTheory.Mantel.ArithmeticGeometricMean
